/**
 * Job Notification Tracker — 60 realistic Indian tech jobs
 */
window.JOBS_DATA = [
  {
    id: "j1",
    title: "SDE Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "Data Structures", "Algorithms"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.amazon.jobs/en/jobs/apply/sde-intern-bangalore",
    description: "Join Amazon's internship program to work on real-world projects. You'll collaborate with experienced engineers, learn best practices, and contribute to services used by millions. Strong problem-solving skills and enthusiasm for learning are essential."
  },
  {
    id: "j2",
    title: "Graduate Engineer Trainee",
    company: "Infosys",
    location: "Mysore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "HTML", "CSS", "JavaScript"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "3–5 LPA",
    applyUrl: "https://career.infosys.com/jobdesc/GET-2025",
    description: "Infosys GET program offers comprehensive training in software development. You will undergo structured learning at our Mysore campus before joining project teams. We look for graduates with strong fundamentals and a passion for technology."
  },
  {
    id: "j3",
    title: "Junior Backend Developer",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Node.js", "PostgreSQL", "Redis", "REST APIs"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "6–10 LPA",
    applyUrl: "https://razorpay.com/careers/junior-backend-developer",
    description: "Build scalable payment infrastructure at Razorpay. You'll work on APIs that process millions of transactions daily. Experience with Node.js and databases is preferred. We value clean code and ownership."
  },
  {
    id: "j4",
    title: "Frontend Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["React", "JavaScript", "HTML", "CSS"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.flipkartcareers.com/frontend-intern",
    description: "Work on user-facing features for India's leading e-commerce platform. You'll use React to build responsive interfaces. Prior internship or project experience with React is a plus."
  },
  {
    id: "j5",
    title: "QA Intern",
    company: "Wipro",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Selenium", "JIRA", "SQL"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.wipro.com/qa-intern-chennai",
    description: "Learn quality assurance practices at Wipro. You'll write test cases, perform manual and automated testing, and work with development teams. Basic understanding of testing concepts is required."
  },
  {
    id: "j6",
    title: "Data Analyst Intern",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "Excel", "Tableau"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.swiggy.com/data-analyst-intern",
    description: "Analyze data to drive decisions at Swiggy. You'll work with large datasets, create dashboards, and support business teams. Proficiency in Python and SQL is expected."
  },
  {
    id: "j7",
    title: "Java Developer (0-1)",
    company: "TCS",
    location: "Mumbai",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "SQL", "REST"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.tcs.com/careers/java-developer-mumbai",
    description: "TCS is hiring Java developers for enterprise projects. You'll work with Spring Boot and microservices. Strong Java fundamentals and willingness to learn are key."
  },
  {
    id: "j8",
    title: "Python Developer (Fresher)",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "Linux"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.zoho.com/careers/python-fresher.html",
    description: "Zoho builds products used globally. As a Python developer, you'll work on web applications and internal tools. We prefer candidates who have built projects in Python."
  },
  {
    id: "j9",
    title: "React Developer (1-3)",
    company: "Freshworks",
    location: "Chennai",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux", "REST APIs"],
    source: "Indeed",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.freshworks.com/company/careers/react-developer",
    description: "Build customer-facing SaaS products at Freshworks. You'll work with React, TypeScript, and modern tooling. Experience with state management and component architecture is required."
  },
  {
    id: "j10",
    title: "SDE Intern",
    company: "Microsoft",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["C++", "Python", "Algorithms", "Problem Solving"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.microsoft.com/sde-intern-hyderabad",
    description: "Microsoft India offers internships in software development. Work on products used by billions. Strong coding skills and ability to learn quickly are essential."
  },
  {
    id: "j11",
    title: "Graduate Engineer Trainee",
    company: "Accenture",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Cloud", "Agile", "SQL"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.accenture.com/in-en/careers/GET",
    description: "Accenture's GET program trains graduates in emerging technologies. You'll work on client projects across industries. Good communication and technical aptitude are important."
  },
  {
    id: "j12",
    title: "Junior Backend Developer",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Kafka", "PostgreSQL", "Microservices"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.phonepe.com/careers/backend-junior",
    description: "Build payment systems at PhonePe. You'll work with high-throughput systems and distributed architecture. Java and database knowledge are required."
  },
  {
    id: "j13",
    title: "Frontend Intern",
    company: "CRED",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "JavaScript", "CSS", "Figma"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://cred.club/careers/frontend-intern",
    description: "Create polished user experiences at CRED. You'll work with designers and backend teams. Attention to detail and React skills are valued."
  },
  {
    id: "j14",
    title: "Data Analyst Intern",
    company: "Paytm",
    location: "Noida",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "SQL", "Excel", "Data Visualization"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://paytm.com/careers/data-analyst-intern",
    description: "Support data-driven decisions at Paytm. You'll analyze user behavior, create reports, and work with analytics tools. SQL and Python proficiency expected."
  },
  {
    id: "j15",
    title: "Java Developer (0-1)",
    company: "Capgemini",
    location: "Pune",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring", "Hibernate", "Oracle"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.capgemini.com/careers/java-developer-pune",
    description: "Capgemini seeks Java developers for enterprise applications. You'll work with Spring and relational databases. Good understanding of OOP and SQL is required."
  },
  {
    id: "j16",
    title: "React Developer (1-3)",
    company: "Juspay",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "JavaScript", "Webpack", "Payment SDKs"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://juspay.io/careers/react-developer",
    description: "Build payment UI components at Juspay. You'll create reusable SDKs used by thousands of apps. Strong React and JavaScript skills are essential."
  },
  {
    id: "j17",
    title: "SDE Intern",
    company: "Google",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["C++", "Python", "Algorithms", "System Design"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.google.com/jobs/sde-intern-india",
    description: "Google's internship program offers exposure to large-scale systems. You'll work on real products with mentorship from experienced engineers. Competitive programming experience is a plus."
  },
  {
    id: "j18",
    title: "Graduate Engineer Trainee",
    company: "Cognizant",
    location: "Coimbatore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Python", "SQL", "Testing"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.cognizant.com/careers/GET-india",
    description: "Cognizant's GET program prepares you for software development roles. Training covers programming, databases, and soft skills. You'll then join project teams."
  },
  {
    id: "j19",
    title: "Junior Backend Developer",
    company: "Dunzo",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Python", "Django", "PostgreSQL", "Redis"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "6–10 LPA",
    applyUrl: "https://dunzo.com/careers/backend-junior",
    description: "Build logistics and delivery systems at Dunzo. You'll work with Python and Django. Understanding of APIs and databases is required."
  },
  {
    id: "j20",
    title: "QA Intern",
    company: "IBM",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Test Automation", "Java", "Selenium", "API Testing"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.ibm.com/careers/qa-intern-bangalore",
    description: "IBM offers QA internships in enterprise software testing. You'll learn automation frameworks and work with development teams. Basic programming knowledge is expected."
  },
  {
    id: "j21",
    title: "Python Developer (Fresher)",
    company: "HackerRank",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "Django", "React", "PostgreSQL"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.hackerrank.com/careers/python-fresher",
    description: "Build the platform that helps millions practice coding. You'll work on full-stack features. Strong Python and problem-solving skills are required."
  },
  {
    id: "j22",
    title: "React Developer (1-3)",
    company: "Postman",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "TypeScript", "Node.js", "REST"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.postman.com/company/careers/react-developer",
    description: "Work on Postman's web application used by developers worldwide. You'll build features for API development. React and TypeScript experience is required."
  },
  {
    id: "j23",
    title: "SDE Intern",
    company: "Oracle",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Cloud", "Linux"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.oracle.com/careers/intern-bangalore",
    description: "Oracle India offers internships in database and cloud technologies. You'll work on enterprise software. Strong fundamentals in programming and databases are expected."
  },
  {
    id: "j24",
    title: "Graduate Engineer Trainee",
    company: "Tech Mahindra",
    location: "Noida",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", ".NET", "SQL", "Testing"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.techmahindra.com/careers/GET",
    description: "Tech Mahindra's GET program trains graduates for IT roles. You'll learn development and testing practices. Good academic record and technical aptitude required."
  },
  {
    id: "j25",
    title: "Junior Backend Developer",
    company: "ShareChat",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Kafka", "Cassandra", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "6–10 LPA",
    applyUrl: "https://sharechat.com/careers/backend-junior",
    description: "Build scalable systems for India's leading social platform. You'll work with high-traffic systems. Java and distributed systems knowledge preferred."
  },
  {
    id: "j26",
    title: "Frontend Intern",
    company: "Zomato",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "JavaScript", "CSS", "Responsive Design"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.zomato.com/careers/frontend-intern",
    description: "Create user experiences for Zomato's web platform. You'll work with React and modern frontend tools. Portfolio with React projects is a plus."
  },
  {
    id: "j27",
    title: "Data Analyst Intern",
    company: "Ola",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "SQL", "Excel", "Power BI"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.olacabs.com/careers/data-intern",
    description: "Analyze mobility data at Ola. You'll create reports and dashboards for business teams. SQL and Python skills are required."
  },
  {
    id: "j28",
    title: "Java Developer (0-1)",
    company: "SAP",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring", "SAP HANA", "REST"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "6–10 LPA",
    applyUrl: "https://jobs.sap.com/java-developer-bangalore",
    description: "SAP seeks Java developers for enterprise solutions. You'll work with SAP technologies and cloud services. Strong Java and database skills are expected."
  },
  {
    id: "j29",
    title: "Python Developer (Fresher)",
    company: "Thoughtworks",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "TDD", "Agile", "Clean Code"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.thoughtworks.com/careers/python-fresher",
    description: "Thoughtworks hires freshers with strong fundamentals. You'll learn agile practices and work on client projects. Passion for software craft is important."
  },
  {
    id: "j30",
    title: "React Developer (1-3)",
    company: "BrowserStack",
    location: "Mumbai",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "JavaScript", "WebRTC", "Testing"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.browserstack.com/careers/react-developer",
    description: "Build testing infrastructure at BrowserStack. You'll work on React applications for developers. Experience with modern frontend tooling is required."
  },
  {
    id: "j31",
    title: "SDE Intern",
    company: "Dell",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Python", "Cloud", "Databases"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://jobs.dell.com/sde-intern-bangalore",
    description: "Dell Technologies offers internships in software development. You'll work on enterprise and cloud solutions. Strong programming fundamentals are required."
  },
  {
    id: "j32",
    title: "Graduate Engineer Trainee",
    company: "L&T Infotech",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Web Technologies", "Testing"],
    source: "Naukri",
    postedDaysAgo: 10,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.lntinfotech.com/careers/GET",
    description: "L&T Infotech's GET program prepares graduates for software roles. You'll undergo training and join project teams. Good academic background is expected."
  },
  {
    id: "j33",
    title: "Junior Backend Developer",
    company: "Meesho",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Python", "Django", "MySQL", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "6–10 LPA",
    applyUrl: "https://meesho.com/careers/backend-junior",
    description: "Build e-commerce backend at Meesho. You'll work on order processing and seller tools. Python and database experience is preferred."
  },
  {
    id: "j34",
    title: "Frontend Intern",
    company: "Unacademy",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "JavaScript", "CSS", "Web Performance"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://unacademy.com/careers/frontend-intern",
    description: "Create learning experiences at Unacademy. You'll build responsive interfaces for education. React and CSS skills are required."
  },
  {
    id: "j35",
    title: "QA Intern",
    company: "MakeMyTrip",
    location: "Gurgaon",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "API Testing", "Postman", "JIRA"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.makemytrip.com/qa-intern",
    description: "Ensure quality of travel products at MakeMyTrip. You'll write test cases and perform API testing. Basic testing knowledge is expected."
  },
  {
    id: "j36",
    title: "Data Analyst Intern",
    company: "PolicyBazaar",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Excel", "Python", "Reporting"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.policybazaar.com/careers/data-intern",
    description: "Analyze insurance and financial data at PolicyBazaar. You'll create reports and support business decisions. SQL and Excel proficiency required."
  },
  {
    id: "j37",
    title: "Java Developer (0-1)",
    company: "HCL Technologies",
    location: "Noida",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring", "Oracle", "REST APIs"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.hcltech.com/careers/java-developer",
    description: "HCL seeks Java developers for enterprise projects. You'll work with Spring and databases. Good Java fundamentals are required."
  },
  {
    id: "j38",
    title: "React Developer (1-3)",
    company: "CleverTap",
    location: "Mumbai",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "Redux", "TypeScript", "GraphQL"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://clevertap.com/careers/react-developer",
    description: "Build analytics dashboards at CleverTap. You'll create data visualization interfaces. React and state management experience is required."
  },
  {
    id: "j39",
    title: "SDE Intern",
    company: "Adobe",
    location: "Noida",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["C++", "JavaScript", "Algorithms", "Data Structures"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.adobe.com/intern-noida",
    description: "Adobe India offers internships in creative and document cloud. You'll work on products used by millions. Strong coding and problem-solving skills are essential."
  },
  {
    id: "j40",
    title: "Graduate Engineer Trainee",
    company: "Mindtree",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Python", "Cloud", "DevOps"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.mindtree.com/careers/GET",
    description: "Mindtree's GET program focuses on digital technologies. You'll learn cloud and modern development practices. Technical aptitude and learning agility are valued."
  },
  {
    id: "j41",
    title: "Junior Backend Developer",
    company: "Instamojo",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["Python", "Django", "PostgreSQL", "Celery"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "6–10 LPA",
    applyUrl: "https://instamojo.com/careers/backend",
    description: "Build payment and e-commerce tools at Instamojo. You'll work with Python and Django. Understanding of web development is required."
  },
  {
    id: "j42",
    title: "Frontend Intern",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "TypeScript", "CSS", "Payment UI"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://razorpay.com/careers/frontend-intern",
    description: "Build payment interfaces at Razorpay. You'll create checkout experiences and dashboards. React and attention to detail are important."
  },
  {
    id: "j43",
    title: "Data Analyst Intern",
    company: "Nykaa",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["SQL", "Python", "Excel", "Data Analysis"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.nykaa.com/careers/data-intern",
    description: "Analyze e-commerce data at Nykaa. You'll support merchandising and marketing teams. SQL and analytical skills are required."
  },
  {
    id: "j44",
    title: "Python Developer (Fresher)",
    company: "Rebel Foods",
    location: "Pune",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "REST"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.rebelfoods.com/careers/python-fresher",
    description: "Build food tech systems at Rebel Foods. You'll work on order and kitchen management. Python and web development knowledge expected."
  },
  {
    id: "j45",
    title: "React Developer (1-3)",
    company: "Livspace",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "JavaScript", "Redux", "Responsive Design"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.livspace.com/careers/react-developer",
    description: "Create home design experiences at Livspace. You'll build configurators and visualization tools. React and UI skills are required."
  },
  {
    id: "j46",
    title: "SDE Intern",
    company: "Intuit",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "SQL", "Algorithms"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.intuit.com/careers/intern-bangalore",
    description: "Work on tax and accounting software at Intuit. You'll contribute to products like TurboTax. Strong programming and problem-solving skills are expected."
  },
  {
    id: "j47",
    title: "Graduate Engineer Trainee",
    company: "Mphasis",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Mainframe", "Testing"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.mphasis.com/careers/GET",
    description: "Mphasis GET program trains graduates for BFSI and technology roles. You'll learn enterprise development. Good academics and technical interest required."
  },
  {
    id: "j48",
    title: "Junior Backend Developer",
    company: "Groww",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["Node.js", "PostgreSQL", "Redis", "Microservices"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "6–10 LPA",
    applyUrl: "https://groww.in/careers/backend-junior",
    description: "Build fintech systems at Groww. You'll work on investment and trading platforms. Node.js and database experience preferred."
  },
  {
    id: "j49",
    title: "Frontend Intern",
    company: "Practo",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "JavaScript", "HTML", "CSS"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.practo.com/careers/frontend-intern",
    description: "Create healthcare interfaces at Practo. You'll build patient and doctor-facing features. React and web fundamentals are required."
  },
  {
    id: "j50",
    title: "QA Intern",
    company: "BigBasket",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Selenium", "Mobile Testing", "JIRA"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.bigbasket.com/careers/qa-intern",
    description: "Ensure quality of grocery platform at BigBasket. You'll test web and mobile apps. Basic testing concepts and attention to detail expected."
  },
  {
    id: "j51",
    title: "Java Developer (0-1)",
    company: "Persistent Systems",
    location: "Pune",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "MongoDB", "Kafka"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.persistent.com/careers/java-developer",
    description: "Persistent hires Java developers for product engineering. You'll work with modern Java stack. Strong fundamentals and learning attitude required."
  },
  {
    id: "j52",
    title: "React Developer (1-3)",
    company: "Slice",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "TypeScript", "Next.js", "GraphQL"],
    source: "Indeed",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://slice.co/careers/react-developer",
    description: "Build fintech products at Slice. You'll create card and payment experiences. React, TypeScript, and modern tooling experience required."
  },
  {
    id: "j53",
    title: "Data Analyst Intern",
    company: "Delhivery",
    location: "Gurgaon",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["SQL", "Python", "Excel", "Logistics Analytics"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.delhivery.com/careers/data-intern",
    description: "Analyze logistics data at Delhivery. You'll support operations and planning teams. SQL and analytical thinking are required."
  },
  {
    id: "j54",
    title: "Python Developer (Fresher)",
    company: "Innovaccer",
    location: "Noida",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "Healthcare", "SQL"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "3–5 LPA",
    applyUrl: "https://innovaccer.com/careers/python-fresher",
    description: "Build healthcare technology at Innovaccer. You'll work on data and analytics platforms. Python and database skills are expected."
  },
  {
    id: "j55",
    title: "SDE Intern",
    company: "VMware",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "Virtualization", "Cloud"],
    source: "LinkedIn",
    postedDaysAgo: 8,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.vmware.com/intern-bangalore",
    description: "VMware offers internships in cloud and virtualization. You'll work on enterprise infrastructure. Strong programming and systems knowledge preferred."
  },
  {
    id: "j56",
    title: "Junior Backend Developer",
    company: "Dealshare",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring", "MySQL", "Redis"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.dealshare.in/careers/backend",
    description: "Build e-commerce backend at DealShare. You'll work on catalog and order systems. Java and database experience is required."
  },
  {
    id: "j57",
    title: "Frontend Intern",
    company: "Cult.fit",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "React Native", "JavaScript", "CSS"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://www.cult.fit/careers/frontend-intern",
    description: "Create fitness and wellness interfaces at Cult.fit. You'll work on web and mobile web. React and JavaScript skills are required."
  },
  {
    id: "j58",
    title: "React Developer (1-3)",
    company: "Acko",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "TypeScript", "Insurance", "Web Apps"],
    source: "Naukri",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.acko.com/careers/react-developer",
    description: "Build insurance technology at Acko. You'll create customer and internal tools. React and TypeScript experience is required."
  },
  {
    id: "j59",
    title: "Graduate Engineer Trainee",
    company: "KPIT",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["C", "Embedded", "Automotive", "Testing"],
    source: "Naukri",
    postedDaysAgo: 10,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.kpit.com/careers/GET",
    description: "KPIT's GET program focuses on automotive and embedded software. You'll learn C and embedded systems. Engineering background in ECE/EEE preferred."
  },
  {
    id: "j60",
    title: "Java Developer (0-1)",
    company: "Info Edge",
    location: "Noida",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring", "Elasticsearch", "MySQL"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.infoedge.com/careers/java-developer",
    description: "Build job and recruitment platforms at Info Edge (Naukri, Jeevansathi). You'll work on search and matching systems. Java and database skills required."
  }
];
